### ISSUE TITLE
[Feature request] Generate valid random names for dirs and files

### ISSUE THREAD

**Issue by julianmesa-gitkraken** [SUPERCILEX/ftzz#12]
It will be great to be able to add an option to generate valid random names choosing a range for the length.
-rn=[10,15]
--random-name=[begin, end]
Or something similar

**Comment by SUPERCILEX** [comment]
Why would file names named numbers from a specific range be more valid than [0, n)? That would also require a different algorithm to determine the number of directories needed since you're limiting the number of files per directory.

**Comment by julianmesa-gitkraken** [comment]
@SUPERCILEX It's not about more valid. I need to load a tree view with a main folder and I need larger names to be able to see horizontal bars, and be sure large names are cut properly (using ellipsys ...)
It is a personal request for my needs

**Comment by SUPERCILEX** [comment]
The problem with a request like this is that it's impossible to satisfy everyone. To solve it correctly would require some kind of DSL or a plugin system that supports arbitrary naming functions. Basically what you're asking for is a `--name-prefix` option, but then someone will come along and ask for a suffix or want the name to be randomly generated, etc.

For your case, I'd suggest just building your own version of ftzz. This is the function you'll want to change:
https://github.com/SUPERCILEX/ftzz/blob/85f8f6db5201381c12d12d837dfad698ef060ed7/src/utils/file_names.rs#L51-L57
It takes in a node ID and maps it to a file name (which right now just means converting the number to a string. For your purposes you could just do something like `f(&format!("my-long-prefix-{i}"))` and not worry about the allocations/performance.
