### ISSUE TITLE
Build of 1.1.0 failed with cargo not finding cli-errors

### ISSUE THREAD

**Issue by BaruchWeka** [SUPERCILEX/ftzz#4]
I tried to build and got the following errors:

```
$ cargo install ftzz
    Updating crates.io index
  Installing ftzz v1.1.0
error: failed to compile `ftzz v1.1.0`, intermediate artifacts can be found at `/tmp/cargo-installCV5Oh1`

Caused by:
  no matching package named `cli-errors` found
  location searched: registry `crates-io`
  required by package `ftzz v1.1.0`
```

I'm on:
* CentOS Linux release 7.9.2009
* rustc 1.64.0 (Red Hat 1.64.0-1.el7)
* cargo 1.64.0

**Comment by SUPERCILEX** [comment]
Oops, sorry about that. I yanked all the cli-errors versions because it's deprecated now that error_stack is a thing, but I thought that was supposed to let existing crates continue working. Anyway, I just started a release build: https://github.com/SUPERCILEX/ftzz/actions/runs/3191940356

**Comment by SUPERCILEX** [comment]
Confirmed that the release worked. Binaries should be statically linked now.
