### ISSUE TITLE
[Feature Request] Consider supporting option to fill files with specified data

### ISSUE THREAD

**Issue by robm-gh** [SUPERCILEX/ftzz#8]
Consider an option (e.g. --fill-byte) that would fill files with the specified byte vs. random bytes.  This would:
1.  potentially make generating the files even faster
2.  make the file content deterministic and compressible

I have zero issues with the speed of ftzz as is.  It's **AMAZING**!  I'm requesting this for #2, but definitely curious about #1
Thank you!

**Comment by SUPERCILEX** [comment]
> I have zero issues with the speed of ftzz as is. It's AMAZING!

Thanks! :)

---

So is the primary goal compressibility? To be clear the file content is deterministic in the same sense as everything else in this repo: the same command will generate the exact same bytes in the same file. This is verified here: https://github.com/SUPERCILEX/ftzz/blob/eb96336ad46592a488c26947d082709c1f073aa7/tests/generator.rs#L301-L305

**Comment by robm-gh** [comment]
You are spot on.  The repeatable nature of the generated data is awesome!  Compressibility is the primary goal.

Thank You!

**Comment by SUPERCILEX** [comment]
Sounds good. Can you share a little bit more about your use case? Is the idea that you're zipping up the generated files and sending them somewhere? I just want to make sure I fully understand the motivation behind compressibility.

**Comment by robm-gh** [comment]
I appreciate you asking!  I want to be able to generate millions of files/directories consuming many (uncompressed) TB/PB, but its footprint is much smaller on a compressed filesystem and/or its compressed backup is much smaller.  So, I'm looking for a huge test dataset that doesn't consume huge amounts of storage.

Thanks much!

**Comment by SUPERCILEX** [comment]
Alrighty, seems reasonable to me. :+1:

I should be able to get to this within a few weeks. Though if you want to take a stab at this, let me know and I'll try to clean up some shitty code + add a bit more docs.

**Comment by github-robm** [comment]
I did tinker with this a bit, but the Rust learning curve is a bit steep for a primarily python guy that hasn't touched a statically typed language in many years :-).

**Comment by SUPERCILEX** [comment]
No worries, I should be able to get to this soon. :)
